# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfos < Formula
  desc "CLI for the DFOS protocol — create identities, publish content, run relays"
  homepage "https://protocol.dfos.com"
  version "0.13.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metalabel/dfos/releases/download/v0.13.6/dfos_0.13.6_darwin_amd64.tar.gz"
      sha256 "64d395f243e423edb8ac6ab72ef182cb6f67b3170309255eb156aa185d4d9044"

      define_method(:install) do
        bin.install "dfos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metalabel/dfos/releases/download/v0.13.6/dfos_0.13.6_darwin_arm64.tar.gz"
      sha256 "78b19f2c470360f9501238230ba8f926d21b045bfccc8c4c80046a41013c60d8"

      define_method(:install) do
        bin.install "dfos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metalabel/dfos/releases/download/v0.13.6/dfos_0.13.6_linux_amd64.tar.gz"
      sha256 "fddb82e24fe6b60e0b5d9cc4313a4a9f32733142a9d6de1aff34c57e2ed8179b"
      define_method(:install) do
        bin.install "dfos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metalabel/dfos/releases/download/v0.13.6/dfos_0.13.6_linux_arm64.tar.gz"
      sha256 "d2e3499cc5d2ae9cb4f1f982cab75a892aa27fdbbb94c7b4032944f7ec8b5560"
      define_method(:install) do
        bin.install "dfos"
      end
    end
  end

  test do
    system "#{bin}/dfos", "version"
  end
end
