# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfos < Formula
  desc "CLI for the DFOS protocol — create identities, publish content, run relays"
  homepage "https://protocol.dfos.com"
  version "0.41.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metalabel/dfos/releases/download/v0.41.0/dfos_0.41.0_darwin_amd64.tar.gz"
      sha256 "44c1d686ead0a3d996528cda9af2da54f3ad057224c1c7432eb57caba06883b7"

      define_method(:install) do
        bin.install "dfos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metalabel/dfos/releases/download/v0.41.0/dfos_0.41.0_darwin_arm64.tar.gz"
      sha256 "3655be5081df1cc9531bf17cc13876b8dc0357637ba5d93e5177b2f93c82c0ca"

      define_method(:install) do
        bin.install "dfos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metalabel/dfos/releases/download/v0.41.0/dfos_0.41.0_linux_amd64.tar.gz"
      sha256 "3192b4298646645483055d940357cbd4c305a557f59254b2f3f56f7cdfa5e75a"
      define_method(:install) do
        bin.install "dfos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metalabel/dfos/releases/download/v0.41.0/dfos_0.41.0_linux_arm64.tar.gz"
      sha256 "91e3b0479f9d76b9bbe7e5c14b659666c9581bbc328ea2edf3c9a728d8fa9f47"
      define_method(:install) do
        bin.install "dfos"
      end
    end
  end

  test do
    system "#{bin}/dfos", "version"
  end
end
